# Generated by Django 5.1.15 on 2026-05-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subway", "0004_step4_5B_schema_align"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="subwaystation",
            new_name="subway_stat_adong_c_77e870_idx",
            old_name="subway_stat_adong_idx",
        ),
        migrations.RenameIndex(
            model_name="subwaystation",
            new_name="subway_stat_ldong_c_9e7181_idx",
            old_name="subway_stat_ldong_idx",
        ),
        migrations.RenameIndex(
            model_name="subwaystation",
            new_name="subway_stat_name_1fcc5b_idx",
            old_name="subway_stat_name_idx",
        ),
        migrations.AlterField(
            model_name="subwaycongestion",
            name="express_yn",
            field=models.CharField(
                help_text="일반/급행 (CHECK ck_subway_congestion_express_yn 2종)", max_length=10
            ),
        ),
    ]
