# Generated by Django 5.1.15 on 2026-05-03 04:01

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("neighborhoods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("convenience", "편의점"),
                            ("mart", "마트"),
                            ("restaurant", "음식점"),
                            ("cafe", "카페"),
                            ("studycafe", "스터디카페"),
                            ("hospital", "병원"),
                            ("pharmacy", "약국"),
                            ("laundry", "세탁소"),
                            ("oliveyoung", "올리브영"),
                            ("park", "공원"),
                            ("etc", "기타"),
                        ],
                        help_text="시설 카테고리 (편의점/카페/공원 등)",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="시설 명칭 (예: 'GS25 충무로점')", max_length=200),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="시설 위치 (WGS84). GiST 인덱스.", srid=4326
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="원천 ID. 소상공인 API의 bizesId 또는 공원 자체 ID. 공원은 null 허용.",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("sba", "소상공인진흥공단"), ("seoul_park", "서울시 도시공원")],
                        help_text="데이터 출처. 'sba' 또는 'seoul_park'.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dong",
                    models.ForeignKey(
                        help_text="사전 매핑된 행정동 (적재 시 spatial join으로 결정)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amenities",
                        to="neighborhoods.dong",
                    ),
                ),
            ],
            options={
                "verbose_name": "생활시설",
                "verbose_name_plural": "생활시설",
                "db_table": "amenity",
                "indexes": [
                    models.Index(fields=["dong", "category"], name="amenity_dong_id_7a8d1d_idx"),
                    models.Index(fields=["category"], name="amenity_categor_4570df_idx"),
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["geom"], name="amenity_geom_gist_idx"
                    ),
                ],
            },
        ),
    ]
