# Generated by Django 5.1.15 on 2026-05-08 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amenities", "0002_kscicategory_businesscategory_store"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="store",
            new_name="store_categor_a63bc0_idx",
            old_name="store_subcate_3bbcf7_idx",
        ),
        migrations.AlterField(
            model_name="store",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_column="category_code",
                help_text="소상공인 소분류 (RDS store.category_code → BusinessCategory.subcategory_code)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stores",
                to="amenities.businesscategory",
            ),
        ),
    ]
