# Generated by Django 5.1.15 on 2026-05-08 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "metric_code",
                    models.CharField(
                        help_text="지표 코드 (RDS metric.metric_code)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="지표 이름", max_length=100)),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="단위 (예: '명', '%', '원')", max_length=30
                    ),
                ),
                ("category", models.CharField(blank=True, help_text="카테고리", max_length=50)),
                ("cycle", models.CharField(blank=True, help_text="갱신 주기", max_length=20)),
                (
                    "is_generated",
                    models.BooleanField(
                        default=False, help_text="생성 지표 여부 (raw가 아닌 파생)"
                    ),
                ),
                ("generation_method", models.TextField(blank=True, help_text="생성 방법 설명")),
                (
                    "source_agency",
                    models.CharField(blank=True, help_text="출처 기관", max_length=100),
                ),
                (
                    "source_table",
                    models.CharField(blank=True, help_text="출처 테이블/통계표", max_length=100),
                ),
                (
                    "source_item",
                    models.CharField(blank=True, help_text="출처 항목명", max_length=200),
                ),
                (
                    "source_classification_code",
                    models.CharField(blank=True, help_text="출처 분류 코드", max_length=100),
                ),
                ("remarks", models.TextField(blank=True, help_text="비고")),
            ],
            options={
                "verbose_name": "지표 메타",
                "verbose_name_plural": "지표 메타",
                "db_table": "metric",
                "ordering": ["metric_code"],
            },
        ),
        migrations.CreateModel(
            name="GuMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(help_text="기준일")),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=6, help_text="지표 값", max_digits=20, null=True
                    ),
                ),
                (
                    "gu",
                    models.ForeignKey(
                        db_column="gu_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="regions.gu",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        db_column="metric_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gu_values",
                        to="metrics.metric",
                    ),
                ),
            ],
            options={
                "verbose_name": "자치구 지표",
                "verbose_name_plural": "자치구 지표",
                "db_table": "gu_metric",
                "ordering": ["-date", "gu_id", "metric_id"],
                "indexes": [
                    models.Index(
                        fields=["gu", "metric", "-date"], name="gu_metric_gu_code_4b2253_idx"
                    ),
                    models.Index(fields=["metric", "-date"], name="gu_metric_metric__546b76_idx"),
                    models.Index(fields=["date"], name="gu_metric_date_669330_idx"),
                ],
                "unique_together": {("gu", "date", "metric")},
            },
        ),
        migrations.CreateModel(
            name="SeoulMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(help_text="기준일")),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=6, help_text="지표 값", max_digits=20, null=True
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        db_column="metric_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seoul_values",
                        to="metrics.metric",
                    ),
                ),
                (
                    "seoul",
                    models.ForeignKey(
                        db_column="seoul_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="regions.seoul",
                    ),
                ),
            ],
            options={
                "verbose_name": "서울 지표",
                "verbose_name_plural": "서울 지표",
                "db_table": "seoul_metric",
                "ordering": ["-date", "metric_id"],
                "indexes": [
                    models.Index(fields=["metric", "-date"], name="seoul_metri_metric__2f3250_idx"),
                    models.Index(fields=["date"], name="seoul_metri_date_43e815_idx"),
                ],
                "unique_together": {("seoul", "date", "metric")},
            },
        ),
    ]
