# Generated by Django 5.1.15 on 2026-05-08 11:11

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("neighborhoods", "0002_alter_dong_code"),
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Park",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="공원 ID (RDS park.id, varchar)",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="공원 이름", max_length=200)),
                ("category", models.CharField(blank=True, help_text="공원 분류", max_length=50)),
                (
                    "area_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="면적 (m^2)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, help_text="공원 경계 (WGS84)", null=True, srid=4326
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, help_text="중심점 (WGS84)", null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "공원",
                "verbose_name_plural": "공원",
                "db_table": "park",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["category"], name="park_categor_4c7933_idx"),
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["boundary"], name="park_boundary_gist_idx"
                    ),
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["location"], name="park_location_gist_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ParkDong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dong",
                    models.ForeignKey(
                        db_column="adong_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="park_dongs",
                        to="neighborhoods.dong",
                        to_field="code",
                    ),
                ),
                (
                    "park",
                    models.ForeignKey(
                        db_column="park_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="park_dongs",
                        to="parks.park",
                    ),
                ),
            ],
            options={
                "verbose_name": "공원-행정동 매핑",
                "verbose_name_plural": "공원-행정동 매핑",
                "db_table": "park_adong",
                "indexes": [
                    models.Index(fields=["park"], name="park_adong_park_id_3c3b3d_idx"),
                    models.Index(fields=["dong"], name="park_adong_adong_c_30d82b_idx"),
                ],
                "unique_together": {("park", "dong")},
            },
        ),
        migrations.CreateModel(
            name="ParkLdong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ldong",
                    models.ForeignKey(
                        db_column="ldong_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="park_ldongs",
                        to="regions.ldong",
                    ),
                ),
                (
                    "park",
                    models.ForeignKey(
                        db_column="park_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="park_ldongs",
                        to="parks.park",
                    ),
                ),
            ],
            options={
                "verbose_name": "공원-법정동 매핑",
                "verbose_name_plural": "공원-법정동 매핑",
                "db_table": "park_ldong",
                "indexes": [
                    models.Index(fields=["park"], name="park_ldong_park_id_8414f7_idx"),
                    models.Index(fields=["ldong"], name="park_ldong_ldong_c_385dc6_idx"),
                ],
                "unique_together": {("park", "ldong")},
            },
        ),
    ]
