# Generated by Django 5.1.15 on 2026-05-02 07:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL용 고유 식별자 (예: 'pildong', 'jung-pildong')",
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="행정동 이름 (예: '필동')", max_length=50)),
                ("gu", models.CharField(help_text="구 이름 (예: '중구')", max_length=50)),
                (
                    "code",
                    models.CharField(help_text="행정동 코드 (행안부, 8~10자리)", max_length=10),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        help_text="행정동 경계 폴리곤 (WGS84)", srid=4326
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="중심점 (WGS84)", srid=4326
                    ),
                ),
                ("area_km2", models.FloatField(default=0, help_text="면적 (km^2)")),
                (
                    "score_rent",
                    models.FloatField(default=0, help_text="전월세 점수 (저렴할수록 높음)"),
                ),
                ("score_amenity", models.FloatField(default=0, help_text="생활시설 점수")),
                ("score_transit", models.FloatField(default=0, help_text="교통 점수")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "행정동",
                "verbose_name_plural": "행정동",
                "db_table": "dong",
                "ordering": ["gu", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="dong_slug_726b5a_idx"),
                    models.Index(fields=["code"], name="dong_code_d90aca_idx"),
                    models.Index(fields=["gu"], name="dong_gu_c36fc1_idx"),
                ],
            },
        ),
    ]
