# Generated by Django 5.1.15 on 2026-05-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neighborhoods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dong",
            name="code",
            field=models.CharField(
                help_text="행정동 코드 (행안부, 8~10자리). RDS adong_code와 동일.",
                max_length=10,
                unique=True,
            ),
        ),
    ]
