# Generated by Django 5.1.15 on 2026-05-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_step4_5B_schema_align"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="store",
            new_name="store_adong_c_b8a0a4_idx",
            old_name="store_adong_idx",
        ),
        migrations.RenameIndex(
            model_name="store",
            new_name="store_ldong_c_a49541_idx",
            old_name="store_ldong_idx",
        ),
        migrations.RenameIndex(
            model_name="store",
            new_name="store_categor_a63bc0_idx",
            old_name="store_category_idx",
        ),
        migrations.RenameIndex(
            model_name="store",
            new_name="store_ksci_co_e67d73_idx",
            old_name="store_ksci_idx",
        ),
    ]
