# Generated by Django 5.1.15 on 2026-05-19 02:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent_deal", "0003_step4_5B_schema_align"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="rentdeal",
            new_name="rent_deal_ldong_c_7caf73_idx",
            old_name="rent_deal_ldong_contract_idx",
        ),
        migrations.RenameIndex(
            model_name="rentdeal",
            new_name="rent_deal_housing_0163a0_idx",
            old_name="rent_deal_htype_contract_idx",
        ),
        migrations.RenameIndex(
            model_name="rentdeal",
            new_name="rent_deal_housing_438bed_idx",
            old_name="rent_deal_htype_idx",
        ),
        migrations.AlterField(
            model_name="rentdeal",
            name="contract_end_date",
            field=models.DateField(blank=True, help_text="계약 종료일", null=True),
        ),
        migrations.AlterField(
            model_name="rentdeal",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="지번 보유 행은 외부 지오코딩 API, 미보유 행은 법정동 centroid (NULL 허용 유지, schema.dbml line 176).",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AlterField(
            model_name="rentdeal",
            name="renewal_request_right_used",
            field=models.BooleanField(blank=True, help_text="갱신요구권 사용 여부", null=True),
        ),
    ]
