# Generated by Django 5.1.15 on 2026-05-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="metric_code",
            field=models.CharField(
                help_text="지표 코드 (RDS metric.metric_code)",
                max_length=30,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
