# Generated by Django 5.1.15 on 2026-05-03 04:01

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("neighborhoods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JibunGeocodeCache",
            fields=[
                (
                    "jibun_text",
                    models.CharField(
                        help_text="정규화된 지번 문자열 (예: '서울특별시 중구 필동2가 84-1')",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="지번 중심점 (WGS84)", srid=4326
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "지번 지오코딩 캐시",
                "verbose_name_plural": "지번 지오코딩 캐시",
                "db_table": "jibun_geocode_cache",
            },
        ),
        migrations.CreateModel(
            name="RentDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "deal_type",
                    models.CharField(
                        choices=[
                            ("apt", "아파트"),
                            ("officetel", "오피스텔"),
                            ("villa", "연립다세대"),
                            ("danok", "단독다가구"),
                        ],
                        help_text="거래 유형 (아파트/오피스텔/연립다세대/단독다가구)",
                        max_length=20,
                    ),
                ),
                ("deal_date", models.DateField(help_text="계약일 (API의 dealYear/Month/Day 조합)")),
                ("area_m2", models.FloatField(help_text="전용면적 (m^2)")),
                ("deposit", models.PositiveIntegerField(help_text="보증금 (만원)")),
                ("monthly_rent", models.PositiveIntegerField(help_text="월세 (만원). 0이면 전세.")),
                (
                    "floor",
                    models.SmallIntegerField(blank=True, help_text="층 (지하 음수)", null=True),
                ),
                (
                    "build_year",
                    models.PositiveSmallIntegerField(blank=True, help_text="건축 연도", null=True),
                ),
                (
                    "jibun",
                    models.CharField(
                        blank=True,
                        help_text="'법정동 + 지번' 원문 (예: '필동2가 84-1')",
                        max_length=64,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="지번 중심점 (VWorld 지오코딩). 매물 단위 정밀 좌표 금지 (SPEC 14.2).",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "external_hash",
                    models.CharField(
                        help_text="멱등 적재용 deal key 해시 (재실행 시 중복 차단)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dong",
                    models.ForeignKey(
                        help_text="법정동→행정동 매핑 후 결정된 행정동",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rent_deals",
                        to="neighborhoods.dong",
                    ),
                ),
            ],
            options={
                "verbose_name": "전월세 실거래",
                "verbose_name_plural": "전월세 실거래",
                "db_table": "rent_deal",
                "ordering": ["-deal_date"],
                "indexes": [
                    models.Index(fields=["dong", "deal_date"], name="rent_deal_dong_id_e5b674_idx"),
                    models.Index(
                        fields=["deal_type", "deal_date"], name="rent_deal_deal_ty_dda379_idx"
                    ),
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["geom"], name="rentdeal_geom_gist_idx"
                    ),
                ],
            },
        ),
    ]
