# Generated by Django 5.1.15 on 2026-05-08 11:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neighborhoods", "0002_alter_dong_code"),
        ("realestate", "0001_initial"),
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentdeal",
            name="contract_end_date",
            field=models.DateField(blank=True, help_text="계약 종료일 (Phase 1 신규)", null=True),
        ),
        migrations.AddField(
            model_name="rentdeal",
            name="contract_type",
            field=models.CharField(
                blank=True, help_text="계약 구분 (신규/갱신 등). Phase 1 신규.", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="rentdeal",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="RDS rent_deal.id (Phase 1 신규). 신규 적재는 이 값으로 멱등 보장.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="rentdeal",
            name="house_name",
            field=models.CharField(
                blank=True, help_text="건물명 (RDS house_name). Phase 1 신규.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="rentdeal",
            name="housing_type",
            field=models.CharField(
                blank=True,
                help_text="RDS housing_type 한글 raw (예: '아파트', '다가구', '연립다세대'). Phase 1 신규.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="rentdeal",
            name="ldong",
            field=models.ForeignKey(
                blank=True,
                help_text="법정동 (Phase 1 신규). RDS ldong_code 직접 매핑.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rent_deals",
                to="regions.ldong",
            ),
        ),
        migrations.AddField(
            model_name="rentdeal",
            name="previous_deposit",
            field=models.PositiveIntegerField(
                blank=True, help_text="종전 계약 보증금 (만원). Phase 1 신규.", null=True
            ),
        ),
        migrations.AddField(
            model_name="rentdeal",
            name="previous_monthly_rent",
            field=models.PositiveIntegerField(
                blank=True, help_text="종전 계약 월세 (만원). Phase 1 신규.", null=True
            ),
        ),
        migrations.AddField(
            model_name="rentdeal",
            name="renewal_request_right_used",
            field=models.BooleanField(
                blank=True, help_text="갱신요구권 사용 여부. Phase 1 신규.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rentdeal",
            name="deal_type",
            field=models.CharField(
                choices=[
                    ("apt", "아파트"),
                    ("officetel", "오피스텔"),
                    ("villa", "연립다세대"),
                    ("dagagu", "다가구"),
                    ("danok", "단독"),
                ],
                help_text="거래 유형 (영문 enum 5종). RDS housing_type 한글 → 영문 derived.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rentdeal",
            name="dong",
            field=models.ForeignKey(
                help_text="법정동→행정동 매핑 후 결정된 행정동. RDS adong_code 또는 location ST_Contains 백필.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rent_deals",
                to="neighborhoods.dong",
            ),
        ),
        migrations.AlterField(
            model_name="rentdeal",
            name="external_hash",
            field=models.CharField(
                blank=True,
                help_text="기존 적재용 deal key 해시 (Phase 1 이전 데이터 호환). 신규 적재는 external_id 사용.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="rentdeal",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="지번 중심점. RDS location 그대로 (SPEC 14.2 정책 충족).",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddIndex(
            model_name="rentdeal",
            index=models.Index(fields=["ldong", "deal_date"], name="rent_deal_ldong_i_c678f0_idx"),
        ),
        migrations.AddIndex(
            model_name="rentdeal",
            index=models.Index(fields=["housing_type"], name="rent_deal_housing_438bed_idx"),
        ),
    ]
