# Generated by Django 5.1.15 on 2026-05-08 11:11

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("neighborhoods", "0002_alter_dong_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seoul",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="서울시 코드 (RDS seoul.code)",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="이름 (예: '서울특별시')", max_length=50)),
                (
                    "area_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="면적 (m^2)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, help_text="서울시 경계 (WGS84)", null=True, srid=4326
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, help_text="중심점 (WGS84)", null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "서울",
                "verbose_name_plural": "서울",
                "db_table": "seoul",
            },
        ),
        migrations.CreateModel(
            name="Gu",
            fields=[
                (
                    "gu_code",
                    models.CharField(
                        help_text="자치구 코드 (RDS gu.gu_code)",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="구 이름 (예: '중구')", max_length=50)),
                (
                    "area_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="면적 (m^2)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, help_text="구 경계 (WGS84)", null=True, srid=4326
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, help_text="중심점 (WGS84)", null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "자치구",
                "verbose_name_plural": "자치구",
                "db_table": "gu",
                "ordering": ["gu_code"],
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["boundary"], name="gu_boundary_gist_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Ldong",
            fields=[
                (
                    "ldong_code",
                    models.CharField(
                        help_text="법정동 코드 (RDS ldong.ldong_code)",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="법정동 이름", max_length=50)),
                (
                    "area_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="면적 (m^2)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, help_text="법정동 경계 (WGS84)", null=True, srid=4326
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, help_text="중심점 (WGS84)", null=True, srid=4326
                    ),
                ),
                (
                    "gu",
                    models.ForeignKey(
                        help_text="속한 자치구 (RDS ldong.gu_code)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ldongs",
                        to="regions.gu",
                    ),
                ),
            ],
            options={
                "verbose_name": "법정동",
                "verbose_name_plural": "법정동",
                "db_table": "ldong",
                "ordering": ["ldong_code"],
            },
        ),
        migrations.CreateModel(
            name="LdongAdjacency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ldong_a",
                    models.ForeignKey(
                        db_column="ldong_code_a",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjacency_a",
                        to="regions.ldong",
                    ),
                ),
                (
                    "ldong_b",
                    models.ForeignKey(
                        db_column="ldong_code_b",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjacency_b",
                        to="regions.ldong",
                    ),
                ),
            ],
            options={
                "verbose_name": "법정동 인접",
                "verbose_name_plural": "법정동 인접",
                "db_table": "adjacent_ldong",
            },
        ),
        migrations.CreateModel(
            name="LdongPopulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(help_text="기준일")),
                (
                    "total_population",
                    models.IntegerField(blank=True, help_text="총 인구", null=True),
                ),
                (
                    "household_count",
                    models.IntegerField(blank=True, help_text="세대 수", null=True),
                ),
                (
                    "male_population",
                    models.IntegerField(blank=True, help_text="남자 인구", null=True),
                ),
                (
                    "female_population",
                    models.IntegerField(blank=True, help_text="여자 인구", null=True),
                ),
                (
                    "ldong",
                    models.ForeignKey(
                        db_column="ldong_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="populations",
                        to="regions.ldong",
                    ),
                ),
            ],
            options={
                "verbose_name": "법정동 인구",
                "verbose_name_plural": "법정동 인구",
                "db_table": "ldong_population",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AdongAdjacency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dong_a",
                    models.ForeignKey(
                        db_column="adong_code_a",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjacency_a",
                        to="neighborhoods.dong",
                        to_field="code",
                    ),
                ),
                (
                    "dong_b",
                    models.ForeignKey(
                        db_column="adong_code_b",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjacency_b",
                        to="neighborhoods.dong",
                        to_field="code",
                    ),
                ),
            ],
            options={
                "verbose_name": "행정동 인접",
                "verbose_name_plural": "행정동 인접",
                "db_table": "adjacent_adong",
                "indexes": [
                    models.Index(fields=["dong_a"], name="adjacent_ad_adong_c_c2bcba_idx"),
                    models.Index(fields=["dong_b"], name="adjacent_ad_adong_c_0eabdf_idx"),
                ],
                "unique_together": {("dong_a", "dong_b")},
            },
        ),
        migrations.CreateModel(
            name="AdongPopulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(help_text="기준일")),
                (
                    "total_population",
                    models.IntegerField(blank=True, help_text="총 인구", null=True),
                ),
                (
                    "household_count",
                    models.IntegerField(blank=True, help_text="세대 수", null=True),
                ),
                (
                    "male_population",
                    models.IntegerField(blank=True, help_text="남자 인구", null=True),
                ),
                (
                    "female_population",
                    models.IntegerField(blank=True, help_text="여자 인구", null=True),
                ),
                (
                    "dong",
                    models.ForeignKey(
                        db_column="adong_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="populations",
                        to="neighborhoods.dong",
                        to_field="code",
                    ),
                ),
            ],
            options={
                "verbose_name": "행정동 인구",
                "verbose_name_plural": "행정동 인구",
                "db_table": "adong_population",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["dong", "-date"], name="adong_popul_adong_c_d66610_idx"),
                    models.Index(fields=["date"], name="adong_popul_date_2c797b_idx"),
                ],
                "unique_together": {("dong", "date")},
            },
        ),
        migrations.CreateModel(
            name="GuAdjacency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "gu_a",
                    models.ForeignKey(
                        db_column="gu_code_a",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjacency_a",
                        to="regions.gu",
                    ),
                ),
                (
                    "gu_b",
                    models.ForeignKey(
                        db_column="gu_code_b",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjacency_b",
                        to="regions.gu",
                    ),
                ),
            ],
            options={
                "verbose_name": "자치구 인접",
                "verbose_name_plural": "자치구 인접",
                "db_table": "adjacent_gu",
                "indexes": [
                    models.Index(fields=["gu_a"], name="adjacent_gu_gu_code_fd88af_idx"),
                    models.Index(fields=["gu_b"], name="adjacent_gu_gu_code_847ccd_idx"),
                ],
                "unique_together": {("gu_a", "gu_b")},
            },
        ),
        migrations.AddIndex(
            model_name="ldong",
            index=models.Index(fields=["gu"], name="ldong_gu_id_9eac56_idx"),
        ),
        migrations.AddIndex(
            model_name="ldong",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["boundary"], name="ldong_boundary_gist_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ldongadjacency",
            index=models.Index(fields=["ldong_a"], name="adjacent_ld_ldong_c_24d643_idx"),
        ),
        migrations.AddIndex(
            model_name="ldongadjacency",
            index=models.Index(fields=["ldong_b"], name="adjacent_ld_ldong_c_04fe42_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="ldongadjacency",
            unique_together={("ldong_a", "ldong_b")},
        ),
        migrations.AddIndex(
            model_name="ldongpopulation",
            index=models.Index(fields=["ldong", "-date"], name="ldong_popul_ldong_c_9123bf_idx"),
        ),
        migrations.AddIndex(
            model_name="ldongpopulation",
            index=models.Index(fields=["date"], name="ldong_popul_date_4249ae_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="ldongpopulation",
            unique_together={("ldong", "date")},
        ),
    ]
