# Generated by Django 5.1.15 on 2026-05-08 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ldong",
            new_name="ldong_gu_code_af3dfe_idx",
            old_name="ldong_gu_id_9eac56_idx",
        ),
        migrations.AlterField(
            model_name="ldong",
            name="gu",
            field=models.ForeignKey(
                db_column="gu_code",
                help_text="속한 자치구 (RDS ldong.gu_code)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ldongs",
                to="regions.gu",
            ),
        ),
    ]
