# Generated by Django 5.1.15 on 2026-05-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0006_step4_5A_schema_align"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adongadjacency",
            new_name="adjacent_ad_adong1__7a7873_idx",
            old_name="adjacent_ad_adong_c_c2bcba_idx",
        ),
        migrations.RenameIndex(
            model_name="adongadjacency",
            new_name="adjacent_ad_adong2__8155e5_idx",
            old_name="adjacent_ad_adong_c_0eabdf_idx",
        ),
        migrations.RenameIndex(
            model_name="guadjacency",
            new_name="adjacent_gu_gu1_cod_11c194_idx",
            old_name="adjacent_gu_gu_code_fd88af_idx",
        ),
        migrations.RenameIndex(
            model_name="guadjacency",
            new_name="adjacent_gu_gu2_cod_ccdc76_idx",
            old_name="adjacent_gu_gu_code_847ccd_idx",
        ),
        migrations.RenameIndex(
            model_name="ldongadjacency",
            new_name="adjacent_ld_ldong1__a4b139_idx",
            old_name="adjacent_ld_ldong_c_24d643_idx",
        ),
        migrations.RenameIndex(
            model_name="ldongadjacency",
            new_name="adjacent_ld_ldong2__08c33b_idx",
            old_name="adjacent_ld_ldong_c_04fe42_idx",
        ),
    ]
