# Generated by Django 5.1.15 on 2026-05-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amenities", "0006_step4_5C_drop_audit_columns"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="amenity",
            name="amenity_dong_id_7a8d1d_idx",
        ),
        migrations.RenameIndex(
            model_name="amenityadong",
            new_name="amenity_ado_amenity_5d63e4_idx",
            old_name="amenity_ado_amenity_idx",
        ),
        migrations.RenameIndex(
            model_name="amenityadong",
            new_name="amenity_ado_adong_c_7226c7_idx",
            old_name="amenity_ado_adong_c_idx",
        ),
        migrations.RenameIndex(
            model_name="amenityldong",
            new_name="amenity_ldo_amenity_6c118b_idx",
            old_name="amenity_ldo_amenity_idx",
        ),
        migrations.RenameIndex(
            model_name="amenityldong",
            new_name="amenity_ldo_ldong_c_9dfdd4_idx",
            old_name="amenity_ldo_ldong_c_idx",
        ),
        migrations.AlterField(
            model_name="amenity",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="name",
            field=models.CharField(
                help_text='시설 명칭. park는 원천 name+" "+park.category 결합 (예: "장미공원 어린이공원"). 그 외는 원천 name 그대로.',
                max_length=200,
            ),
        ),
    ]
