# Generated by Django 5.1.15 on 2026-05-03 04:01

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("neighborhoods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubwayStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="역명 (예: '충무로')", max_length=50)),
                ("line", models.CharField(help_text="노선 (예: '3호선')", max_length=20)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="서울 OpenAPI 역 ID (있으면)",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="역 위치 (WGS84). GiST 인덱스.", srid=4326
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "지하철역",
                "verbose_name_plural": "지하철역",
                "db_table": "subway_station",
                "ordering": ["line", "name"],
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["geom"], name="subway_geom_gist_idx"
                    )
                ],
                "unique_together": {("name", "line")},
            },
        ),
        migrations.CreateModel(
            name="BusStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="정류장 명칭", max_length=100)),
                (
                    "arsId",
                    models.CharField(
                        blank=True, help_text="정류소번호 (서울 BIS arsId)", max_length=10
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="정류장 위치 (WGS84). GiST 인덱스.", srid=4326
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dong",
                    models.ForeignKey(
                        help_text="사전 매핑된 행정동",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bus_stops",
                        to="neighborhoods.dong",
                    ),
                ),
            ],
            options={
                "verbose_name": "버스 정류장",
                "verbose_name_plural": "버스 정류장",
                "db_table": "bus_stop",
                "indexes": [
                    models.Index(fields=["dong"], name="bus_stop_dong_id_e3c5f2_idx"),
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["geom"], name="busstop_geom_gist_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NearestSubway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(help_text="1~3")),
                ("distance_m", models.FloatField(help_text="동 centroid → 역 직선 거리 (m)")),
                (
                    "dong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nearest_subways",
                        to="neighborhoods.dong",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dong_rankings",
                        to="transit.subwaystation",
                    ),
                ),
            ],
            options={
                "verbose_name": "가까운 지하철역 (사전계산)",
                "verbose_name_plural": "가까운 지하철역 (사전계산)",
                "db_table": "nearest_subway",
                "ordering": ["dong", "rank"],
                "unique_together": {("dong", "rank")},
            },
        ),
    ]
