# Generated by Django 5.1.15 on 2026-05-08 11:11

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neighborhoods", "0002_alter_dong_code"),
        ("regions", "0001_initial"),
        ("transit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusCongestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(help_text="기준일")),
                ("time", models.TimeField(help_text="시간대")),
                (
                    "congestion",
                    models.DecimalField(
                        blank=True, decimal_places=4, help_text="혼잡도", max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "버스 혼잡도",
                "verbose_name_plural": "버스 혼잡도",
                "db_table": "bus_congestion",
            },
        ),
        migrations.CreateModel(
            name="SubwayCongestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day_type", models.CharField(help_text="평일/토요일/일요일", max_length=10)),
                ("direction", models.CharField(help_text="상선/하선", max_length=10)),
                ("express_yn", models.CharField(help_text="일반/급행", max_length=10)),
                ("time", models.TimeField(help_text="시간대")),
                (
                    "congestion",
                    models.DecimalField(
                        decimal_places=4, help_text="혼잡도 (numeric NOT NULL)", max_digits=10
                    ),
                ),
            ],
            options={
                "verbose_name": "지하철 혼잡도",
                "verbose_name_plural": "지하철 혼잡도",
                "db_table": "subway_congestion",
            },
        ),
        migrations.RenameIndex(
            model_name="busstop",
            new_name="bus_stop_adong_c_711295_idx",
            old_name="bus_stop_dong_id_e3c5f2_idx",
        ),
        migrations.AddField(
            model_name="busstop",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="RDS bus_stop.id (Phase 1 신규). RDS PK 1:1.",
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="busstop",
            name="ldong",
            field=models.ForeignKey(
                blank=True,
                db_column="ldong_code",
                help_text="법정동 (Phase 1 신규, RDS ldong_code).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bus_stops",
                to="regions.ldong",
            ),
        ),
        migrations.AddField(
            model_name="subwaystation",
            name="dong",
            field=models.ForeignKey(
                blank=True,
                db_column="adong_code",
                help_text="행정동 (Phase 1 신규, RDS adong_code).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subway_stations",
                to="neighborhoods.dong",
                to_field="code",
            ),
        ),
        migrations.AddField(
            model_name="subwaystation",
            name="ldong",
            field=models.ForeignKey(
                blank=True,
                db_column="ldong_code",
                help_text="법정동 (Phase 1 신규, RDS ldong_code).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subway_stations",
                to="regions.ldong",
            ),
        ),
        migrations.AlterField(
            model_name="busstop",
            name="arsId",
            field=models.CharField(
                blank=True,
                help_text="정류소번호 (서울 BIS arsId). RDS stop_number 1:1.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="busstop",
            name="dong",
            field=models.ForeignKey(
                blank=True,
                db_column="adong_code",
                help_text="행정동 (Phase 1: nullable로 완화. RDS 95% 매핑, 5%는 좌표 보강).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bus_stops",
                to="neighborhoods.dong",
                to_field="code",
            ),
        ),
        migrations.AlterField(
            model_name="subwaystation",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="RDS subway_station.id (Phase 1: unique 제약).",
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="busstop",
            index=models.Index(fields=["ldong"], name="bus_stop_ldong_c_33a3d6_idx"),
        ),
        migrations.AddIndex(
            model_name="busstop",
            index=models.Index(fields=["arsId"], name="bus_stop_arsId_a3e096_idx"),
        ),
        migrations.AddIndex(
            model_name="subwaystation",
            index=models.Index(fields=["dong"], name="subway_stat_adong_c_77e870_idx"),
        ),
        migrations.AddIndex(
            model_name="subwaystation",
            index=models.Index(fields=["ldong"], name="subway_stat_ldong_c_9e7181_idx"),
        ),
        migrations.AddField(
            model_name="buscongestion",
            name="bus_stop",
            field=models.ForeignKey(
                db_column="bus_stop_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="congestions",
                to="transit.busstop",
            ),
        ),
        migrations.AddField(
            model_name="subwaycongestion",
            name="station",
            field=models.ForeignKey(
                db_column="station_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="congestions",
                to="transit.subwaystation",
            ),
        ),
        migrations.AddIndex(
            model_name="buscongestion",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["date"], name="buscongestion_date_brin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="buscongestion",
            index=models.Index(fields=["bus_stop", "-date"], name="bus_congest_bus_sto_c2984d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="buscongestion",
            unique_together={("bus_stop", "date", "time")},
        ),
        migrations.AddIndex(
            model_name="subwaycongestion",
            index=models.Index(
                fields=["station", "day_type"], name="subway_cong_station_43fb82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subwaycongestion",
            index=models.Index(fields=["day_type", "time"], name="subway_cong_day_typ_f2d5b8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="subwaycongestion",
            unique_together={("station", "day_type", "direction", "express_yn", "time")},
        ),
    ]
