# Generated by Django 5.1.15 on 2026-05-08 15:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transit", "0002_buscongestion_subwaycongestion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busstop",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="정류장 위치 (WGS84). GiST 인덱스. RDS에 NULL 719건 존재.",
                null=True,
                srid=4326,
            ),
        ),
    ]
