# Generated by Django 5.1.15 on 2026-05-02 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neighborhoods", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True,
                default="",
                help_text="표시용 닉네임. 카카오 profile_nickname이 들어오거나, 직접 입력. 빈 값이면 username을 그대로 노출.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.CharField(
                blank=True,
                default="",
                help_text="학교명 (예: '동국대학교'). 카카오 가입 후 사용자가 직접 입력.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="year",
            field=models.IntegerField(
                blank=True, help_text="학년 (1~6 정도). null = 미입력.", null=True
            ),
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="neighborhoods.dong",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "찜한 동네",
                "verbose_name_plural": "찜한 동네",
                "db_table": "user_favorite",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="user_favori_user_id_9351bd_idx"
                    )
                ],
                "unique_together": {("user", "dong")},
            },
        ),
    ]
