# Generated by Django 5.1.15 on 2026-05-19 02:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus", "0003_step4_5B_schema_align"),
        (
            "regions",
            "0007_rename_adjacent_ad_adong_c_c2bcba_idx_adjacent_ad_adong1__7a7873_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="busstop",
            new_name="bus_stop_adong_c_711295_idx",
            old_name="bus_stop_adong_idx",
        ),
        migrations.RenameIndex(
            model_name="busstop",
            new_name="bus_stop_ldong_c_33a3d6_idx",
            old_name="bus_stop_ldong_idx",
        ),
        migrations.RenameIndex(
            model_name="busstop",
            new_name="bus_stop_stop_nu_874697_idx",
            old_name="bus_stop_stop_num_idx",
        ),
        migrations.AlterField(
            model_name="buscongestion",
            name="time",
            field=models.TimeField(help_text="시간대 0~23"),
        ),
        migrations.AlterField(
            model_name="busstop",
            name="ldong",
            field=models.ForeignKey(
                blank=True,
                db_column="ldong_code",
                help_text="법정동 (nullable).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bus_stops",
                to="regions.ldong",
            ),
        ),
        migrations.AlterField(
            model_name="busstop",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="정류장 위치 (WGS84). 매칭 불가 시 NULL 보존 (가상·차고지·미정차 등, schema.dbml line 249).",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AlterField(
            model_name="busstop",
            name="name",
            field=models.CharField(help_text="정류장 명칭 (NOT NULL)", max_length=100),
        ),
    ]
